# Bismillahir Rahmanir Rahim
# Rabbi Zidni Ilma 

from ScalableNaiveBayes import ScalableNaiveBayes
import pickle

def main():
    
    nb = pickle.load(open('./models/modelall5/model.p','rb'))

    print(nb.predict(['MKRSISFRPTLLALVLATNFPVAHAAVPKDMLVIGKAADPQTLDPAVTIDNNDWTVTYPSYQRLVQYKTDGDKGSTDVEGDLASSWKASDDQKEWTFTLKDNAKFADGTPVTAEAVKLSFERLLKIGQGPAEAFPKDLKIDAPDEHTVKFTLSQPFAPFLYTLANDGASIINPAVLKEHAADDARGFLAQNTAGSGPFMLKSWQKGQQLVLVPNPHYPGNKPNFKRVSVKIIGESASRRLQLSRGDIDIADALPVDQLNALKQENKVNVAEYPSLRVTYLYLNNSKAPLNQADLRRAISWSTDYQGMVNGILSGNGKQMRGPIPEGMWGYDATAMQYNHDETKAKAEWDKVTSKPTSLTFLYSDNDPNWEPIALATQSSLNKLGIIVKLEKLANATMRDRVGKGDYDIAIGNWSPDFADPYMFMNYWFESDKKGLPGNRSFYENSEVDKLLRNALATTDQTQRTRDYQQAQKIVIDDAAYVYLFQKNYQLAMNKEVKGFVFNPMLEQVFNINTMSK']))

if __name__ == '__main__':
    main()